<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwvKAGd\testsSymfonyLab_Tests_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwvKAGd/testsSymfonyLab_Tests_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRwvKAGd.legacy');

    return;
}

if (!\class_exists(testsSymfonyLab_Tests_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRwvKAGd\testsSymfonyLab_Tests_TestKernelTestDebugContainer::class, testsSymfonyLab_Tests_TestKernelTestDebugContainer::class, false);
}

return new \ContainerRwvKAGd\testsSymfonyLab_Tests_TestKernelTestDebugContainer([
    'container.build_hash' => 'RwvKAGd',
    'container.build_id' => 'b71b116b',
    'container.build_time' => 1573818874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwvKAGd');
