<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'symfonylab_customer_io.tracker' shared service.

include_once $this->targetDirs[4].'/vendor/psr/log/Psr/Log/LoggerAwareInterface.php';
include_once $this->targetDirs[4].'/vendor/psr/log/Psr/Log/LoggerAwareTrait.php';
include_once $this->targetDirs[4].'/src/Tracking/EventTracker.php';

return $this->privates['symfonylab_customer_io.tracker'] = new \SymfonyLab\CustomerIOBundle\Tracking\EventTracker(($this->privates['symfonylab_customer_io.api'] ?? $this->load('getSymfonylabCustomerIo_ApiService.php')));
